Fixed UI breaking on narrow screens
N1ck/gifs-for-github pull request #79
Opened 2024-08-03 15:19 UTC by Jonghakseo

### AS-IS

<img width="554" alt="스크린샷 2024-08-04 오전 12 16 11" src="https://github.com/user-attachments/assets/6f6ea44f-4de0-4192-9648-6850ba31895f">

### TO-BE

<img width="487" alt="스크린샷 2024-08-04 오전 12 16 28" src="https://github.com/user-attachments/assets/c4d40832-7403-41a4-b0b0-c2b39e7ca4aa">

2025-03-24 04:21 UTC, N1ck requested changes
Thanks for the PR to solve this, it is annoying on narrow screens that it drops to a new line, I'd like to look for a more robust solution, however.

2025-03-24 04:21 UTC, N1ck commented on src/main.js
> +        toolbarGroup.prepend(clonedNode)
Many of us are used to having the GIF button where it is 😅 Ideally I think we'd look at how to add the GIF button to the `...` overflow menu.

2025-12-08 11:01 UTC, ToshY commented
@Jonghakseo @N1ck Any update on this PR? Still experiencing this issue on `25.10.13`.

2026-02-13 20:40 UTC, PatrykKuniczak commented
@N1ck Are you able to fix it?
That's really annoying, and it's easy to fix.

2026-04-20 20:12 UTC, PatrykKuniczak commented
Let's do sth with that, that's easy to fix, as Joghak shown
Why it shouldn't be merged @N1ck ?

2026-04-21 03:47 UTC, N1ck commented
> Let's do sth with that, that's easy to fix, as Joghak shown Why it shouldn't be merged @N1ck ?

Hey @PatrykKuniczak, I haven't had a chance to revisit this myself yet, but I do still have reservations about the current approach.

My concern is that swapping `append` for `prepend` just moves the button rather than solving the underlying layout issue, and as I mentioned a while back, it's disruptive for users who are used to the GIF button's current position.

What I'd really like is for the button to fall into the `...` overflow menu when the toolbar gets too narrow. That would be a more robust fix that doesn't change anything for users on wider screens. I'd be open to a PR going in that direction if anyone wants to take a crack at it.

2026-04-22 00:51 UTC, closed without merging